site_name: NearIT Cordova
theme: readthedocs
extra_css : ["css/nearitdocs.css"]
pages:
    - 'Getting started' : 'index.md'
    - 'User Guide' :
        - 'Installation' : 'installation.md'
        - 'Enable Triggers' : 'enable-triggers.md'
        - 'Handle recipe content' : 'handle-content.md'
        - 'User profiling' : 'user-profilation.md'
    - 'Advanced topics' :
        - 'Android Push notifications' : 'fcm_walkthrough.md'
        - 'iOS Push certificates' : 'apns_walkthrough.md'
